In [33]:
#Import Libraries

import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [34]:
df = pd.read_csv("/content/processed_sms_dataset.csv")

df.head()

,label,text,text_length,clean_text_basic,clean_text_advanced,text_no_stopwords,normalized_text,final_clean_text
0,ham,"Go until jurong point, crazy.. Available only ...",111,go until jurong point crazy available only in ...,go until jurong point crazy available only in ...,go jurong point crazy available bugis n great ...,go jurong point crazy available bugis n great ...,go jurong point crazy available bugis n great ...
1,ham,Ok lar... Joking wif u oni...,29,ok lar joking wif u oni,ok lar joking wif u oni,ok lar joking wif u oni,ok lar joking wif you oni,ok lar joking wif you oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,155,free entry in a wkly comp to win fa cup final ...,free entry in a wkly comp to win fa cup final ...,free entry wkly comp win fa cup final tkts st ...,free entry wkly comp win fa cup final tkts st ...,free entry wkly comp win fa cup final tkts st ...
3,ham,U dun say so early hor... U c already then say...,49,u dun say so early hor u c already then say,u dun say so early hor u c already then say,u dun say early hor u c already say,you dun say early hor you c already say,you dun say early hor you c already say
4,ham,"Nah I don't think he goes to usf, he lives aro...",61,nah i dont think he goes to usf he lives aroun...,nah i dont think he goes to usf he lives aroun...,nah dont think goes usf lives around though,nah dont think goes usf lives around though,nah dont think go usf life around though

In [35]:
#Task 1: Manual One-Hot Encoding
sentences = df["final_clean_text"].head(5).tolist()   #selecting the 5 sentences

for i, sentence in enumerate(sentences, 1):
    print(f"Sentence {i}: {sentence}")


#build the vocabulary

vocabulary = sorted(set(word for sentence in sentences for word in sentence.split()))

print("Vocabulary:\n")
print(vocabulary)
print("\nVocabulary Size:", len(vocabulary))

Sentence 1: go jurong point crazy available bugis n great world la e buffet cine got amore wat
Sentence 2: ok lar joking wif you oni
Sentence 3: free entry wkly comp win fa cup final tkts st may text fa receive entry questionstd txt ratetcs apply over
Sentence 4: you dun say early hor you c already say
Sentence 5: nah dont think go usf life around though
Vocabulary:

['already', 'amore', 'apply', 'around', 'available', 'buffet', 'bugis', 'c', 'cine', 'comp', 'crazy', 'cup', 'dont', 'dun', 'e', 'early', 'entry', 'fa', 'final', 'free', 'go', 'got', 'great', 'hor', 'joking', 'jurong', 'la', 'lar', 'life', 'may', 'n', 'nah', 'ok', 'oni', 'over', 'point', 'questionstd', 'ratetcs', 'receive', 'say', 'st', 'text', 'think', 'though', 'tkts', 'txt', 'usf', 'wat', 'wif', 'win', 'wkly', 'world', 'you']

Vocabulary Size: 53

In [36]:
#Create One-Hot Vectors
one_hot_vectors = []

for sentence in sentences:
    vector = {}
    words = sentence.split()
    for word in vocabulary:
        vector[word] = 1 if word in words else 0
    one_hot_vectors.append(vector)

#Display One-Hot Matrix
one_hot_df = pd.DataFrame(one_hot_vectors)
one_hot_df

,already,amore,apply,around,available,buffet,bugis,c,cine,comp,...,though,tkts,txt,usf,wat,wif,win,wkly,world,you
0,0,1,0,0,1,1,1,0,1,0,...,0,0,0,0,1,0,0,0,1,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
2,0,0,1,0,0,0,0,0,0,1,...,0,1,1,0,0,0,1,1,0,0
3,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,1,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0

In [37]:
#Task 2: One-Hot Encoding using Scikit-learn

binary_vectorizer = CountVectorizer(binary=True)
binary_matrix = binary_vectorizer.fit_transform(sentences)

#vocabulary
print("Vocabulary:\n")
print(binary_vectorizer.vocabulary_)

binary_df = pd.DataFrame(binary_matrix.toarray(),columns=binary_vectorizer.get_feature_names_out())
binary_df

Vocabulary:

{'go': 18, 'jurong': 23, 'point': 32, 'crazy': 9, 'available': 4, 'bugis': 6, 'great': 20, 'world': 48, 'la': 24, 'buffet': 5, 'cine': 7, 'got': 19, 'amore': 1, 'wat': 44, 'ok': 29, 'lar': 25, 'joking': 22, 'wif': 45, 'you': 49, 'oni': 30, 'free': 17, 'entry': 14, 'wkly': 47, 'comp': 8, 'win': 46, 'fa': 15, 'cup': 10, 'final': 16, 'tkts': 41, 'st': 37, 'may': 27, 'text': 38, 'receive': 35, 'questionstd': 33, 'txt': 42, 'ratetcs': 34, 'apply': 2, 'over': 31, 'dun': 12, 'say': 36, 'early': 13, 'hor': 21, 'already': 0, 'nah': 28, 'dont': 11, 'think': 39, 'usf': 43, 'life': 26, 'around': 3, 'though': 40}

,already,amore,apply,around,available,buffet,bugis,cine,comp,crazy,...,though,tkts,txt,usf,wat,wif,win,wkly,world,you
0,0,1,0,0,1,1,1,1,0,1,...,0,0,0,0,1,0,0,0,1,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
2,0,0,1,0,0,0,0,0,1,0,...,0,1,1,0,0,0,1,1,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,1,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0

### Observation

In manual one-hot encoding, each unique word in the vocabulary is assigned a binary value indicating whether it is present in a sentence. Using CountVectorizer(binary=True) produces the same result automatically and is more efficient for larger datasets.

In [38]:
bow_vectorizer = CountVectorizer()
# Fit and transform the complete dataset after filling NaN values with empty strings
bow_matrix = bow_vectorizer.fit_transform(df["final_clean_text"].fillna(''))
vocabulary = bow_vectorizer.get_feature_names_out()
print("Vocabulary Size:", len(vocabulary))

#display te 20words
print("First 20 Words in Vocabulary:\n")
print(vocabulary[:20])

bow_df = pd.DataFrame(bow_matrix.toarray(),columns=bow_vectorizer.get_feature_names_out())
bow_df.head()

print("Sample Feature Vectors:\n")
bow_df.head(5)

Vocabulary Size: 7732
First 20 Words in Vocabulary:

['aa' 'aah' 'aaniye' 'aaoright' 'aathilove' 'aathiwhere' 'ab' 'abbey'
 'abdomen' 'abeg' 'abel' 'aberdeen' 'abi' 'ability' 'abiola' 'abj' 'able'
 'abnormally' 'aboutas' 'abroad']
Sample Feature Vectors:

,aa,aah,aaniye,aaoright,aathilove,aathiwhere,ab,abbey,abdomen,abeg,...,zed,zero,zf,zhong,zindgi,zoe,zogtorius,zoom,zouk,zyada
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [39]:
#Task 4: Understanding Word Frequency

word_frequency = bow_df.sum(axis=0)
frequency_df = pd.DataFrame({"Word": word_frequency.index,"Frequency": word_frequency.values})
frequency_df.head()

top_words = frequency_df.sort_values(by="Frequency",ascending=False).head(10)
top_words

least_words = frequency_df.sort_values(by="Frequency").head(10)
least_words

           Word  Frequency
7730       zouk          1
7729       zoom          1
7728  zogtorius          1
7726     zindgi          1
7725      zhong          1
7724         zf          1
7723       zero          1
7721      zebra          1
7720    zealand          1
7719     zahers          1

## Observation

The Bag of Words model represents each document by counting the number of times each word appears. Frequently occurring words receive higher counts, while words that appear rarely have lower counts. This representation captures word frequency but does not preserve the order or context of words.

In [40]:
#Task 5: Unigrams, Bigrams & Trigrams

# Unigram Vectorizer
unigram_vectorizer = CountVectorizer(ngram_range=(1, 1))

unigram_matrix = unigram_vectorizer.fit_transform(df["final_clean_text"].fillna(''))

print("Unigram Vocabulary Size:", len(unigram_vectorizer.get_feature_names_out()))
print()

unigram_df = pd.DataFrame(
    unigram_matrix.toarray(),
    columns=unigram_vectorizer.get_feature_names_out()
)
unigram_df.head()

# Bigram Vectorizer
bigram_vectorizer = CountVectorizer(ngram_range=(2, 2))
bigram_matrix = bigram_vectorizer.fit_transform(df["final_clean_text"].fillna(''))

print("Bigram Vocabulary Size:", len(bigram_vectorizer.get_feature_names_out()))
print()

bigram_df = pd.DataFrame(
    bigram_matrix.toarray(),
    columns=bigram_vectorizer.get_feature_names_out()
)
bigram_df.head()

# Trigram Vectorizer
trigram_vectorizer = CountVectorizer(ngram_range=(3, 3))
trigram_matrix = trigram_vectorizer.fit_transform(df["final_clean_text"].fillna(''))

print("Trigram Vocabulary Size:", len(trigram_vectorizer.get_feature_names_out()))
print()

trigram_df = pd.DataFrame(
    trigram_matrix.toarray(),
    columns=trigram_vectorizer.get_feature_names_out()
)
trigram_df.head()

comparison = pd.DataFrame({
    "Vectorizer": ["Unigram", "Bigram", "Trigram"],
    "Vocabulary Size": [
        len(unigram_vectorizer.get_feature_names_out()),
        len(bigram_vectorizer.get_feature_names_out()),
        len(trigram_vectorizer.get_feature_names_out())]})
comparison

Unigram Vocabulary Size: 7732

Bigram Vocabulary Size: 30163

Trigram Vocabulary Size: 30713

  Vectorizer  Vocabulary Size
0    Unigram             7732
1     Bigram            30163
2    Trigram            30713

In [41]:
#Task 6: Combined N-Grams

combined_vectorizer = CountVectorizer(ngram_range=(1, 2))
combined_matrix = combined_vectorizer.fit_transform(df["final_clean_text"].fillna(''))

print("Combined Vocabulary Size:",
      len(combined_vectorizer.get_feature_names_out()))

combined_df = pd.DataFrame(
    combined_matrix.toarray(),
    columns=combined_vectorizer.get_feature_names_out()
)
combined_df.head()

Combined Vocabulary Size: 37895

,aa,aa exhaust,aah,aah bless,aah cuddle,aah speak,aaniye,aaniye pudunga,aaoright,aaoright work,...,zoe hit,zoe join,zogtorius,zogtorius ive,zoom,zoom cine,zouk,zouk nichols,zyada,zyada kisi
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Observation

- Unigrams represent individual words.
- Bigrams capture relationships between two consecutive words.
- Trigrams preserve even more context by considering three consecutive words.
- Combining unigrams and bigrams provides richer contextual information while still retaining individual word frequencies.

In [42]:
#Task 7: TF-IDF Implementation

# Create TF-IDF Vectorizer
tfidf_vectorizer = TfidfVectorizer()
# Fit and transform the dataset
tfidf_matrix = tfidf_vectorizer.fit_transform(df["final_clean_text"].fillna(''))

print("Vocabulary Size:", len(tfidf_vectorizer.get_feature_names_out()))
print("\nFirst 20 Vocabulary Words:\n")
print(tfidf_vectorizer.get_feature_names_out()[:20])
print("TF-IDF Matrix Shape:", tfidf_matrix.shape)

tfidf_df = pd.DataFrame(tfidf_matrix.toarray(),columns=tfidf_vectorizer.get_feature_names_out())

tfidf_df.head()

Vocabulary Size: 7732

First 20 Vocabulary Words:

['aa' 'aah' 'aaniye' 'aaoright' 'aathilove' 'aathiwhere' 'ab' 'abbey'
 'abdomen' 'abeg' 'abel' 'aberdeen' 'abi' 'ability' 'abiola' 'abj' 'able'
 'abnormally' 'aboutas' 'abroad']
TF-IDF Matrix Shape: (5572, 7732)

,aa,aah,aaniye,aaoright,aathilove,aathiwhere,ab,abbey,abdomen,abeg,...,zed,zero,zf,zhong,zindgi,zoe,zogtorius,zoom,zouk,zyada
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [43]:
#Task 8: BoW vs TF-IDF Comparison

comparison_words = ["free", "call", "please", "win", "love"]
comparison_df = pd.DataFrame({"BoW Frequency": bow_df[comparison_words].sum(),"TF-IDF Weight": tfidf_df[comparison_words].mean()})
comparison_df

average_scores = tfidf_df.mean(axis=0)
high_tfidf = average_scores.sort_values(ascending=False).head(10)
high_tfidf

low_tfidf = average_scores.sort_values().head(10)
low_tfidf

theseyours                                 0.000017
sankranti                                  0.000017
ugadi                                      0.000017
shivratri                                  0.000017
dasara                                     0.000017
independence                               0.000017
friendshipmotherfatherteacherschildrens    0.000017
republic                                   0.000017
rememberi                                  0.000017
approaching                                0.000017
dtype: float64

## Observation

Bag of Words stores only the frequency of words in each document. TF-IDF assigns higher importance to words that appear frequently in a document but rarely across the entire dataset. As a result, common words receive lower weights while informative words receive higher weights.

In [44]:
#Task 9: Vectorizer Parameter Exploration
vectorizer_max = CountVectorizer(max_features=100)
vectorizer_max.fit(df["final_clean_text"].fillna(''))

print("Vocabulary Size with max_features=100:")
print(len(vectorizer_max.get_feature_names_out()))

vectorizer_min = CountVectorizer(min_df=2)
vectorizer_min.fit(df["final_clean_text"].fillna(''))

print("Vocabulary Size with min_df=2:")
print(len(vectorizer_min.get_feature_names_out()))

vectorizer_maxdf = CountVectorizer(max_df=0.8)
vectorizer_maxdf.fit(df["final_clean_text"].fillna(''))

print("Vocabulary Size with max_df=0.8:")
print(len(vectorizer_maxdf.get_feature_names_out()))

Vocabulary Size with max_features=100:
100
Vocabulary Size with min_df=2:
3485
Vocabulary Size with max_df=0.8:
7732

In [45]:
parameter_df = pd.DataFrame({
    "Parameter": ["Default","max_features=100","min_df=2","max_df=0.8"],
    "Vocabulary Size": [
        len(bow_vectorizer.get_feature_names_out()),
        len(vectorizer_max.get_feature_names_out()),
        len(vectorizer_min.get_feature_names_out()),
        len(vectorizer_maxdf.get_feature_names_out())]})
parameter_df

          Parameter  Vocabulary Size
0           Default             7732
1  max_features=100              100
2          min_df=2             3485
3        max_df=0.8             7732

Task 10
1. One-Hot Encoding represents only whether a word is present or absent in a sentence. Bag of Words represents the number of times each word appears in a document

2. N-Grams generate combinations of consecutive words, creating many additional features. As the value of N increases, the vocabulary grows significantly, resulting in higher-dimensional feature vectors

3. TF-IDF is preferred when common words should have less influence and important words should receive higher importance. It often performs better in text classification and information retrieval tasks

4. Ignores word meaning.
- Ignores word order (except N-Grams).
- Produces sparse vectors.
- Cannot understand context or semantic relationships